<?php

namespace Modules\System\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Modules\System\Models\Menu;

class MenuItemsSeeder extends Seeder
{
    public function run()
    {
        $menuItems = [
            [
                'id' => 1,
                'title' => json_encode(['en' => 'Dashboard']),
                'prefix' => 'dashboard',
                'icon' => 'dashboard',
                'url' => '#',
                'order' => 1,
                'parent_id' => null,
                'created_at' => '2024-07-26 00:35:53',
                'updated_at' => '2024-07-26 05:01:51',
            ],
            [
                'id' => 2,
                'title' => json_encode(['en' => 'General']),
                'prefix' => null,
                'icon' => 'dashboard',
                'url' => 'dashboard',
                'order' => 1,
                'parent_id' => 1,
                'created_at' => '2024-07-26 00:36:12',
                'updated_at' => '2024-07-26 05:02:10',
            ],
            [
                'id' => 3,
                'title' => json_encode(['en' => 'User & Roles']),
                'prefix' => 'iam',
                'icon' => null,
                'url' => '#',
                'order' => 2,
                'parent_id' => null,
                'created_at' => '2024-07-26 02:01:15',
                'updated_at' => '2024-07-26 05:02:56',
            ],
            [
                'id' => 4,
                'title' => json_encode(['en' => 'Users']),
                'prefix' => null,
                'icon' => null,
                'url' => 'iam/users',
                'order' => 1,
                'parent_id' => 3,
                'created_at' => '2024-07-26 02:02:47',
                'updated_at' => '2024-07-26 05:03:22',
            ],
            [
                'id' => 5,
                'title' => json_encode(['en' => 'Roles']),
                'prefix' => null,
                'icon' => '',
                'url' => 'iam/roles',
                'order' => 2,
                'parent_id' => 3,
                'created_at' => '2024-07-26 02:03:13',
                'updated_at' => '2024-07-26 05:03:50',
            ],
            [
                'id' => 6,
                'title' => json_encode(['en' => 'Permissions']),
                'prefix' => null,
                'icon' => null,
                'url' => 'iam/permissions',
                'order' => 3,
                'parent_id' => 3,
                'created_at' => '2024-07-26 02:03:33',
                'updated_at' => '2024-07-26 05:04:01',
            ],
            [
                'id' => 7,
                'title' => json_encode(['en' => 'Permission Groups']),
                'prefix' => null,
                'icon' => null,
                'url' => 'iam/permission-groups',
                'order' => 4,
                'parent_id' => 3,
                'created_at' => '2024-07-26 02:04:06',
                'updated_at' => '2024-07-26 05:04:17',
            ],
            [
                'id' => 8,
                'title' => json_encode(['en' => 'Items Management']),
                'prefix' => 'inventory',
                'icon' => null,
                'url' => '#',
                'order' => 3,
                'parent_id' => null,
                'created_at' => '2024-07-26 02:05:00',
                'updated_at' => '2024-07-26 06:05:25',
            ],
            [
                'id' => 9,
                'title' => json_encode(['en' => 'Items']),
                'prefix' => null,
                'icon' => null,
                'url' => 'inventory/items',
                'order' => 1,
                'parent_id' => 8,
                'created_at' => '2024-07-26 02:05:11',
                'updated_at' => '2024-07-26 06:05:16',
            ],
            [
                'id' => 10,
                'title' => json_encode(['en' => 'Item Categories']),
                'prefix' => null,
                'icon' => null,
                'url' => 'inventory/item-categories',
                'order' => 2,
                'parent_id' => 8,
                'created_at' => '2024-07-26 02:06:00',
                'updated_at' => '2024-07-26 06:06:19',
            ],
            [
                'id' => 13,
                'title' => json_encode(['en' => 'Business']),
                'prefix' => 'business',
                'icon' => 'dashboard',
                'url' => '#',
                'order' => 7,
                'parent_id' => null,
                'created_at' => '2024-08-09 12:24:26',
                'updated_at' => '2024-09-28 14:45:50',
            ],
            [
                'id' => 14,
                'title' => json_encode(['en' => 'Business Settings']),
                'prefix' => '',
                'icon' => 'dashboard',
                'url' => 'business/business-settings',
                'order' => 1,
                'parent_id' => 13,
                'created_at' => '2024-08-09 12:24:58',
                'updated_at' => '2024-08-09 12:24:58',
            ],
            [
                'id' => 15,
                'title' => json_encode(['en' => 'Business Partners']),
                'prefix' => '',
                'icon' => '',
                'url' => 'business/business-partners',
                'order' => 2,
                'parent_id' => 13,
                'created_at' => '2024-08-09 12:26:49',
                'updated_at' => '2024-08-09 12:26:49',
            ],
            [
                'id' => 16,
                'title' => json_encode(['en' => 'Sponsors']),
                'prefix' => '',
                'icon' => '',
                'url' => 'business/sponsors',
                'order' => 3,
                'parent_id' => 13,
                'created_at' => '2024-08-09 12:27:14',
                'updated_at' => '2024-08-09 12:27:14',
            ],
            [
                'id' => 17,
                'title' => json_encode(['en' => 'CRM']),
                'prefix' => 'crm',
                'icon' => null,
                'url' => '#',
                'order' => 5,
                'parent_id' => null,
                'created_at' => '2024-09-02 09:18:17',
                'updated_at' => '2024-09-02 09:18:17',
            ],
            [
                'id' => 18,
                'title' => json_encode(['en' => 'Leads']),
                'prefix' => '',
                'icon' => null,
                'url' => 'crm/leads',
                'order' => 1,
                'parent_id' => 17,
                'created_at' => '2024-09-02 09:18:40',
                'updated_at' => '2024-09-02 09:18:40',
            ],
            [
                'id' => 19,
                'title' => json_encode(['en' => 'Opportunities']),
                'prefix' => '',
                'icon' => null,
                'url' => 'crm/opportunities',
                'order' => 2,
                'parent_id' => 17,
                'created_at' => '2024-09-02 09:19:02',
                'updated_at' => '2024-09-27 13:51:09',
            ],
            [
                'id' => 20,
                'title' => json_encode(['en' => 'Customers']),
                'prefix' => '',
                'icon' => null,
                'url' => 'crm/customers',
                'order' => 3,
                'parent_id' => 17,
                'created_at' => '2024-09-02 09:19:26',
                'updated_at' => '2024-09-27 13:51:39',
            ],
            [
                'id' => 22,
                'title' => json_encode(['en' => 'Selling']),
                'prefix' => 'selling',
                'icon' => null,
                'url' => '#',
                'order' => 6,
                'parent_id' => null,
                'created_at' => '2024-09-28 12:40:32',
                'updated_at' => '2024-09-28 12:40:32',
            ],
            [
                'id' => 23,
                'title' => json_encode(['en' => 'Sales Order']),
                'prefix' => '',
                'icon' => null,
                'url' => 'selling/sales-orders',
                'order' => 1,
                'parent_id' => 22,
                'created_at' => '2024-09-28 13:08:07',
                'updated_at' => '2024-09-28 13:08:07',
            ],
            [
                'id' => 27,
                'title' => json_encode(['en' => 'Sales Invoices']),
                'prefix' => null,
                'icon' => null,
                'url' => 'selling/sales-invoices',
                'order' => 2,
                'parent_id' => 22,
                'created_at' => '2024-09-28 14:27:09',
                'updated_at' => '2024-09-28 14:27:09',
            ],
            [
                'id' => 29,
                'title' => json_encode(['en' => 'Global Settings']),
                'prefix' => 'global',
                'icon' => null,
                'url' => '#',
                'order' => 8,
                'parent_id' => null,
                'created_at' => '2024-09-28 14:42:31',
                'updated_at' => '2024-09-28 14:42:31',
            ],
            [
                'id' => 30,
                'title' => json_encode(['en' => 'Reference Schemas']),
                'prefix' => '',
                'icon' => null,
                'url' => 'global/reference-schemas',
                'order' => 1,
                'parent_id' => 29,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
            [
                'id' => 31,
                'title' => json_encode(['en' => 'Accounting']),
                'prefix' => 'accounting',
                'icon' => null,
                'url' => '#',
                'order' => 6,
                'parent_id' => null,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
            [
                'id' => 32,
                'title' => json_encode(['en' => 'Expenses']),
                'prefix' => '',
                'icon' => null,
                'url' => 'accounting/expenses',
                'order' => 1,
                'parent_id' => 31,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
            [
                'id' => 33,
                'title' => json_encode(['en' => 'Expense Categories']),
                'prefix' => '',
                'icon' => null,
                'url' => 'accounting/expense-categories',
                'order' => 2,
                'parent_id' => 31,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
            [
                'id' => 34,
                'title' => json_encode(['en' => 'Customer Support']),
                'prefix' => 'customer-support',
                'icon' => null,
                'url' => '#',
                'order' => 7,
                'parent_id' => null,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
            [
                'id' => 35,
                'title' => json_encode(['en' => 'Support Requests']),
                'prefix' => '',
                'icon' => null,
                'url' => 'customer-support/support-requests',
                'order' => 1,
                'parent_id' => 34,
                'created_at' => '2024-09-28 14:42:52',
                'updated_at' => '2024-09-28 14:42:52',
            ],
        ];

        foreach ($menuItems as $item) {
            DB::table('menu_items')->updateOrInsert(
                ['id' => $item['id']],     // Match by primary key or unique key
                $item                      // Values to update if exists, or insert if not
            );
        }

        // Ensure menu exists (create if needed)
        $menu = Menu::firstOrCreate(['id' => 1], ['name' => ['en' => 'Admin Menu']]);

        // Get IDs of all menu items
        $menuItemIds = DB::table('menu_items')->pluck('id');

        // Attach items without duplicating entries
        $menu->items()->syncWithoutDetaching($menuItemIds);
    }
}
